### ISSUE TITLE
Faster ed25519 library?

### ISSUE THREAD

**Issue by Chjango** [tendermint/ed25519#11]
Have we considered linking to https://github.com/floodyberry/ed25519-donna?

It seems like it would be faster.

**Comment by ebuchman** [comment]
Probably not worth the C++ dependency

**Comment by ValarDragon** [comment]
I'd much rather stick to the pure golang implementation and use ASM directly. Probably will be even faster than donna's, since we'd be writing the minimal instruction set in assembly. Theres already a golang CL for this. Ref https://github.com/tendermint/tendermint/issues/1923

Also switching to C++ would make doing the many public key decompression / verification caching optimizations much harder. I think we should definitely stick to golang w/ ASM instructions.

**Comment by ebuchman** [comment]
Ok let's close this. Also note we're going to move to use https://github.com/tendermint/crypto/tree/master/ed25519 ala https://github.com/tendermint/tendermint/issues/1959
